[phases.setup]
nixPkgs = ["python310", "nodejs-18_x"]

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt",
  "cd app && npm install"
]

[phases.build]
cmds = [
  "cd app && npm run build"
]

[start]
cmd = "cd backend && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app"
